#!/bin/bash
set -Eeo pipefail

# shellcheck disable=2154
trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR

reArgsMaybe="^[^:[:space:]]+:.*$" # Smallest indication of attempt to use argument
reArgSkip='^([[:blank:]]*#.*|[[:blank:]]*)$' # comment or empty line

# Paths
userConfPath="/etc/sftp/users.conf"
userConfPathLegacy="/etc/sftp-users.conf"
userConfFinalPath="/var/run/sftp/users.conf"

function log() {
    echo "[$0] $*" >&2
}

# Allow running other programs, e.g. bash
if [[ -z "$1" || "$1" =~ $reArgsMaybe ]]; then
    startSshd=true
else
    startSshd=false
fi

# Mount S3FS
if [ ! -f "/run/secrets/S3_ACCESS_KEY_ID" ]; then
    log "FATAL: No S3 access key id provided!"
    exit 3
fi
if [ ! -f "/run/secrets/S3_SECRET_ACCESS_KEY" ]; then
    log "FATAL: No S3 secret access key provided!"
    exit 3
fi
echo "$(cat /run/secrets/S3_ACCESS_KEY_ID):$(cat /run/secrets/S3_SECRET_ACCESS_KEY)" > /etc/passwd-s3fs
chmod 600 /etc/passwd-s3fs
mkdir /s3
s3fs -o allow_other $S3_BUCKET /s3 -o endpoint=$S3_REGION

# Backward compatibility with legacy config path
if [ ! -f "$userConfPath" ] && [ -f "$userConfPathLegacy" ]; then
    mkdir -p "$(dirname $userConfPath)"
    ln -s "$userConfPathLegacy" "$userConfPath"
fi

# Create users only on first run
if [ ! -f "$userConfFinalPath" ]; then
    mkdir -p "$(dirname $userConfFinalPath)"

    if [ -f "$userConfPath" ]; then
        # Append mounted config to final config
        grep -v -E "$reArgSkip" < "$userConfPath" > "$userConfFinalPath"
    fi

    if $startSshd; then
        # Append users from arguments to final config
        for user in "$@"; do
            echo "$user" >> "$userConfFinalPath"
        done
    fi

    if [ -n "$SFTP_USERS" ]; then
        # Append users from environment variable to final config
        IFS=" " read -r -a usersFromEnv <<< "$SFTP_USERS"
        for user in "${usersFromEnv[@]}"; do
            echo "$user" >> "$userConfFinalPath"
        done
    fi

    # Check that we have users in config
    if [ -f "$userConfFinalPath" ] && [ "$(wc -l < "$userConfFinalPath")" -gt 0 ]; then
        # Import users from final conf file
        while IFS= read -r user || [[ -n "$user" ]]; do
            create-sftp-user "$user"
        done < "$userConfFinalPath"
    elif $startSshd; then
        log "FATAL: No users provided!"
        exit 3
    fi

    # Move secrets ssh keys for this container if they exist
    if [ -f /run/secrets/ssh_host_ed25519_key ]; then
        cp /run/secrets/ssh_host_ed25519_key /etc/ssh/
        chmod 400 /etc/ssh/ssh_host_ed25519_key
    fi
    if [ -f /run/secrets/ssh_host_rsa_key ]; then
        cp /run/secrets/ssh_host_rsa_key /etc/ssh/
        chmod 400 /etc/ssh/ssh_host_rsa_key
    fi

    # Generate unique ssh keys for this container, if needed
    if [ ! -f /etc/ssh/ssh_host_ed25519_key ]; then
        ssh-keygen -t ed25519 -f /etc/ssh/ssh_host_ed25519_key -N ''
    fi
    if [ ! -f /etc/ssh/ssh_host_rsa_key ]; then
        ssh-keygen -t rsa -b 4096 -f /etc/ssh/ssh_host_rsa_key -N ''
    fi
fi

# Mount S3 in each users 'uploads' folder
for d in /home/*/ ; do
    user=$(basename $d)
    mkdir -p "/s3/$user/uploads"
    mkdir -p "/home/$user/uploads"
    mount --bind "/s3/$user/uploads" "/home/$user/uploads"
    chown -R "$user:users" "/s3/$user/uploads"
done

# Source custom scripts, if any
if [ -d /etc/sftp.d ]; then
    for f in /etc/sftp.d/*; do
        if [ -x "$f" ]; then
            log "Running $f ..."
            $f
        else
            log "Could not run $f, because it's missing execute permission (+x)."
        fi
    done
    unset f
fi

if $startSshd; then
    log "Executing sshd"
    exec /usr/sbin/sshd -D -e
else
    log "Executing $*"
    exec "$@"
fi
